In [1]:
import pandas as pd
import numpy as np

In [4]:
banks = pd.read_excel(r"C:\Users\prana\Downloads\All banks - consolidated.xlsx")

In [5]:
banks.head()

,Unnamed: 0,Unnamed: 1,Interest Earned,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,EXPENDITURE,Unnamed: 8,Unnamed: 9,...,Public Share Holding,Unnamed: 34,Unnamed: 35,a) Pledged/Encumbered,Unnamed: 37,Unnamed: 38,b) Non-encumbered,Unnamed: 40,Unnamed: 41,Unnamed: 42
0,Quarterly Results of Federal Bank (in Rs. Cr.),Bank,(a) Int. /Disc. on Adv/Bills,(b) Income on Investment,(c) Int. on balances With RBI,others,Other Income,Interest Expended,Employees Cost,Other Expenses,...,No Of Shares (Crores),Share Holding (%),Promoters and Promoter Group Shareholding,- Number of shares (Crores),- Per. of shares (as a % of the total sh. of p...,- Per. of shares (as a % of the total Share Ca...,- Number of shares (Crores).,- Per. of shares (as a % of the total sh. of p...,- Per. of shares (as a % of the total Share Ca...,yrc
1,Dec '19,Federal Bank,"2,702.78",536.11,35.27,56.20,407.86,"2,175.43",414.76,404.21,...,--,--,NaN,--,--,--,--,--,--,201912
2,Sep '19,Federal Bank,"2,637.66",527.44,38.11,51.04,420.92,"2,130.47",440.70,385.20,...,--,--,NaN,--,--,--,--,--,--,201909
3,Jun '19,Federal Bank,"2,606.08",555.23,19.72,48.27,391.52,"2,075.13",397.84,365.09,...,--,--,NaN,--,--,--,--,--,--,201906
4,Mar '19,Federal Bank,"2,413.05",536.38,11.78,71.11,411.72,"1,935.79",370.15,383.35,...,--,--,NaN,--,--,--,--,--,--,201903